### ISSUE TITLE
Android studio can't find java.awt.Color

### ISSUE THREAD

**Issue by Mr-Wurter** [hoijui/JavaOSC#51] opened 2020-01-04 11:37 UTC
When using this project on Android studio, when trying to send a message using an OSCPortOut, I get an NoClassDefFoundException for java.awt.Color, which is necessary for the serializer. Is there any way to fix this?

**Comment by Burtan** [comment] 2020-01-11 12:02
Either use version 0.4 or use my custom version, which is unfortunately not available via maven, as I'm waiting for the pull request to be accepted:
https://github.com/hoijui/JavaOSC/pull/49

**Comment by hoijui** [comment] 2020-03-28 20:32
solved by pull request https://github.com/hoijui/JavaOSC/pull/49 by @Burtan, now merged into `master`

**Closed by hoijui** 2020-03-28 20:32 UTC

**Comment by Burtan** [comment] 2020-04-05 15:46
Any plans about releasing this with 0.7?

**Comment by hoijui** [comment] 2020-04-06 14:13
good idea!
for now I made a `SNAPSHOT-0.7` release.

**Comment by Burtan** [comment] 2020-04-07 16:42
Not sure if I'm doing something wrong or the release didn't work. I have added the snapshot sonatype repository and could find:
`"com.illposed.osc", "javaosc-parent", "0.7-SNAPSHOT"`
but not
`"com.illposed.osc", "javaosc-core", "0.7-SNAPSHOT"`
Until now I had the dependency on 
`"com.illposed.osc", "javaosc-core", "0.6"`
But the parent module doesn't seem to have the core as a dependency. 
I'm using gradle 6.2.2

**Comment by hoijui** [comment] 2020-04-07 17:09
Took me some time too, but.. you would have to add the nexus/sonatype snapshot repository in your gradle file. in maven it goes like this:

_pom.xml_:

``` xml
	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
	</distributionManagement>
```

in _build.gradle_, (I think) like this:

```
repositories {
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
        mavenContent {
            snapshotsOnly()
        }
    }
}
```

**Comment by Burtan** [comment] 2020-04-08 15:49
The problem is not the repository but the javaosc core module missing from the repo?

**Comment by hoijui** [comment] 2020-04-08 19:07
well... it worked for me like this (using maven). after deleting the locally installed snapshot versions, it downloaded it from that repo.
maybe the gradle code is wrong then?

**Comment by Burtan** [comment] 2020-04-09 16:48
Yeah, the repo looks fine:
https://oss.sonatype.org/content/repositories/snapshots/com/illposed/osc/
So it must be gradle. I'll keep you updated when I find the problem.

**Comment by Burtan** [comment] 2020-04-09 17:19
This works
`implementation("com.illposed.osc", "javaosc-core", "0.7-20200407.165423-5")`
Seems to be some weird gradle SNAPSHOT interaction

**Comment by hoijui** [comment] 2020-04-10 06:59
thank you! :-)
... and that is indeed very strange.. and very unpractical!
how would I tell someone to use the latest snapshot in gradle?
how could we document it?
